### ISSUE TITLE
Keywords

### ISSUE THREAD

**Issue by beck24** [dhenderson/ntee#1]
Hey thanks for this!

My project needs the keywords for each code that can be found on the individual pages - http://www.nccsdataweb.urban.org/PubApps/nteeSearch.php?returnElement=&popup=0&gQry=X20&codeType=NTEE

You don't happen to have those handy by chance do you?

If not I'm going to be scraping them shortly, would you accept a PR with those?

**Comment by dhenderson** [comment]
I didn't pull the keywords but would definitely accept a PR with those. Thanks!

**Comment by dhenderson** [comment]
Added keywords and descriptions for NTEE codes from http://nccsweb.urban.org/PubApps/nteeSearch.php?codeType=
